name: Security Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run audit daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Run NPM audit
        run: npm audit --audit-level=moderate
        continue-on-error: true
      
      - name: Check for outdated dependencies
        run: |
          echo "📦 Checking for outdated dependencies..."
          npx npm-check-updates --format table || true
      
      - name: License compatibility check
        run: |
          echo "📜 Checking license compatibility..."
          npx license-checker --summary --excludePrivatePackages || true
  
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          deny-licenses: GPL-3.0, AGPL-3.0
          comment-summary-in-pr: always